### ISSUE TITLE
Display bugs on mobile

### ISSUE THREAD

**Issue by AuxiliumCDNG** [Programmier-AG/BeeLogger#80]
BeeLogger site on mobile has some problems...

e.g.:
![355B3EB1-2788-412B-B774-2008DC3193B3](https://user-images.githubusercontent.com/47604750/139597534-7d5304c9-fad9-4adf-b700-99c056eb899e.JPG)

**Comment by fabiancdng** [comment]
That doesn't look too good :/
I'll have a look soon.
