### ISSUE TITLE
Front End / Back End: Bring back weather forecast / at least current weather display

### ISSUE THREAD

**Issue by fabiancdng** [Programmier-AG/BeeLogger#90]
I think it might be a good idea to bring back a weather forecast or at least current weather display on the BeeLogger dashboard.

The best way of doing this, I think, is by fetching a weather API in the back end (!) and rendering the weather display on the server-side by using Flask's templating functionality. We have to come up with some sort of caching though as we can't fetch the 3rd party API with every request to the dashboard. Maybe your background tasks thingy could query the API every hour or so and save the current weather (forecast) to a text file?

**Comment by AuxiliumCDNG** [comment]
#93
